spring.application.name=andianaApi
server.port=8090
spring.datasource.url=jdbc:postgresql://localhost:5433/Andiana
spring.datasource.username=postgres
spring.datasource.password=Uisrael.
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=none
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false
